In [1]:
#Assignment 0 - Section A

import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([-1, 1, 3])

#2A-B
print(2 * A - B)

#magnitude of A
mag_A = np.sqrt( np.sum(i * i for i in A))
print(np.sqrt( np.sum(i * i for i in A)))
print(np.linalg.norm(A))

#unit vector in the direction of A
a = [i/mag_A for i in A]
print(a)

#direction cosines of A 
print(np.rad2deg(np.arccos(a)))

# A.B and B.A
print(np.dot(A, B))
print(np.dot(B, A))

#angle between A and B
print(np.rad2deg(np.arccos(np.dot(A, B) / (np.sqrt( np.sum(i * i for i in A)) * np.sqrt( np.sum(i * i for i in B))) )))

#vector perpendicular to A
#assuming x = y = 1
z = (-1*A[0] - 1*A[1])/A[2]
pV_A = np.array([1, 1, z])
print(pV_A)

#AXB and BXA
print(np.cross(A, B))
print(np.cross(B, A))

#vector perpendicular to both A and B
print(np.cross(A, B))

# ATranpose B and ABTranspose
print(np.dot(np.transpose(A),B))
print(A.dot(np.transpose(B)))

[-2 -1  0]
3.74165738677
3.74165738677
[0.2672612419124244, 0.53452248382484879, 0.80178372573727319]
[ 74.49864043  57.68846676  36.6992252 ]
32
32
12.9331544919
[ 1.  1. -1.]
[-3  6 -3]
[ 3 -6  3]
[-3  6 -3]
32
32


In [2]:
#Assignment 0 - Section B

A = np.array([[1, 2, 3], [4, -2, 3] , [0, 5, -1]])
B = np.array([[1, 2, 1], [2, 1, -4] , [3, -2, 1]])
C = np.array([[1, 2, 3], [4, 5, 6], [-1, 1, 3]])
#2A-B 
print(2*A - B)

#AB
AB = np.matmul(A, B)
print(AB)

#BA
print(np.matmul(B, A))

#(AB)Transpose
print(np.transpose(AB))

#BtAt
Bt = np.transpose(B)
At = np.transpose(A)
BtAt = np.matmul(Bt, At)
print(BtAt)

#|A| and |C|
print(np.linalg.det(A))
print(np.linalg.det(C))

#Ainverse and Binverse
print(np.linalg.inv(A))
print(np.linalg.inv(B))

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]
[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
55.0
7.49400541622e-16
[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [3]:
#Assignment 0 - Section C

A = np.array([[1,2], [3, 2]])
B = np.array([[2, -2], [-2, 5]])

W, V = np.linalg.eig(A)
print(W)
print(V)

print(np.matmul(np.linalg.inv(V),np.matmul(A, V)))

print( np.dot( np.array([V[0][0],V[1][0]]), np.array([V[0][1],V[1][1]]) ) )


WB, VB = np.linalg.eig(B)
print(WB)
print(VB)

print(np.matmul(np.linalg.inv(VB),np.matmul(B, VB)))

print( np.dot( np.array([VB[0][0],VB[1][0]]), np.array([VB[0][1],VB[1][1]]) ) )


[-1.  4.]
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
[[ -1.00000000e+00  -6.66133815e-16]
 [  0.00000000e+00   4.00000000e+00]]
-0.196116135138
[ 1.  6.]
[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]
[[  1.00000000e+00  -4.44089210e-16]
 [  1.66533454e-16   6.00000000e+00]]
0.0


In [4]:
M = np.array([[3,0,0], [0,2,0], [0,0,1]])
print(np.linalg.inv(M))

[[ 0.33333333  0.          0.        ]
 [ 0.          0.5         0.        ]
 [ 0.          0.          1.        ]]
